name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++
    - name: Build project
      run: g++ -o my_program hello.cpp
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-program-executable
        path: my_program
    
