name: C/C++ CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

    - name: Install g++ compiler
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Verify g++ version
      run: g++ --version

    - name: Build hello1.cpp -> hello1.out
      run: |
        g++ -o hello1.out hello1.cpp

    - name: Build hello2.cpp -> hello2.out
      run: |
        g++ -o hello2.out hello2.cpp

    - name: Build hello3.cpp -> hello3.out
      run: |
        g++ -o hello3.out hello3.cpp

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: my_program

    - name: Configure git to use GitHub Actions token
      run: |
        git config --local user.email "mane.ghudratyan@gmail.com"
        git config --local user.name "ManGhudratyan"
