name: C/C++ CI

on: 
  workflow_dispatch:   

permissions:
  contents: write

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file_name: [hello1.cpp, hello2.cpp, hello3.cpp]
        output_file_name: [my_program1, my_program2, my_program3]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build project
      run: g++ -o ${{ matrix.output_file_name }} ${{ matrix.file_name }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.output_file_name }}
        path: ${{ matrix.output_file_name }}

    - name: Configure git to use GitHub Actions token
      run: |
        git config --local user.email "mane.ghudratyan@gmail.com"
        git config --local user.name "ManGhudratyan"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git


