name: C/C++ CI

on:
 workflow_dispatch:


# env:
#   FILE_NAME: index.cpp

permissions:
  contents: write
 
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # OUTPUT_FILE: [{in: hello1.cpp, out: hello1.out }, {in: hello2.cpp, out: hello2.out }, {in: hello3.cpp, out: hello3.out }]
         files:
          - hello1.cpp:hello1.out
          - hello2.cpp:hello2.out
          - hello3.cpp:hello3.out
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install g++ compiler
      run: sudo apt-get update && sudo apt-get install -y g++
    - name: Verify g++ version
      run: g++ --version
    - name: Build project
      run: |
         IFS=":" read -r input_file output_file <<< "${{ matrix.files }}"
         echo "Building $input_file -> $output_file"
         g++ -o $output_file $input_file
           
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
       name: my-artifact
       path: my_program        
    - name: Configure git to use GitHub Actions token
      run: |
          git config --local user.email "mane.ghudratyan@gmail.com"
          git config --local user.name "ManGhudratyan"
